modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="notsoshrimple"
version="1.2"
displayName="Not So Shrimple"
logoFile="icon.png"
credits="Very special thanks to Alpha, Gec Master#7889 for the model and textures!"
authors="Peeko32213"
description='''
It's Kinda shrimple if you think about it
'''

[[dependencies.notsoshrimple]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.notsoshrimple]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.notsoshrimple]]
modId="geckolib"
mandatory=true
versionRange="[4.2.3,)"
ordering="BEFORE"
side="BOTH"